// <auto-generated />
using KTGIUAKY.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KTGIUAKY.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KTGIUAKY.Models.DishCategory_BCS240047", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DishCategories_BCS240047");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Các món ăn nhẹ khai vị",
                            Name = "Món khai vị"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Các món ăn chính",
                            Name = "Món chính"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Các món tráng miệng ngọt",
                            Name = "Món tráng miệng"
                        });
                });

            modelBuilder.Entity("KTGIUAKY.Models.DishImage_BCS240047", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DishId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsThumbnail")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DishId");

                    b.ToTable("DishImages_BCS240047");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DishId = 1,
                            ImageUrl = "/images/salad.jpg",
                            IsThumbnail = true
                        },
                        new
                        {
                            Id = 2,
                            DishId = 2,
                            ImageUrl = "/images/supcua.jpg",
                            IsThumbnail = true
                        },
                        new
                        {
                            Id = 3,
                            DishId = 3,
                            ImageUrl = "/images/bonuong.jpg",
                            IsThumbnail = true
                        },
                        new
                        {
                            Id = 4,
                            DishId = 4,
                            ImageUrl = "/images/comchien.jpg",
                            IsThumbnail = true
                        },
                        new
                        {
                            Id = 5,
                            DishId = 5,
                            ImageUrl = "/images/kemdau.jpg",
                            IsThumbnail = true
                        });
                });

            modelBuilder.Entity("KTGIUAKY.Models.Dish_BCS240047", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DishCategoryId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("PreparationTime")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DishCategoryId");

                    b.HasIndex("Name", "DishCategoryId")
                        .IsUnique();

                    b.ToTable("Dishes_BCS240047");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Salad rau tươi trộn dầu giấm",
                            DishCategoryId = 1,
                            IsAvailable = true,
                            Name = "Salad rau trộn",
                            PreparationTime = 10,
                            Price = 35000m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Súp cua thơm ngon",
                            DishCategoryId = 1,
                            IsAvailable = true,
                            Name = "Súp cua",
                            PreparationTime = 15,
                            Price = 45000m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Bò nướng lá lốt thơm lừng",
                            DishCategoryId = 2,
                            IsAvailable = true,
                            Name = "Bò nướng lá lốt",
                            PreparationTime = 25,
                            Price = 120000m
                        },
                        new
                        {
                            Id = 4,
                            Description = "Cơm chiên với tôm, mực",
                            DishCategoryId = 2,
                            IsAvailable = true,
                            Name = "Cơm chiên hải sản",
                            PreparationTime = 20,
                            Price = 85000m
                        },
                        new
                        {
                            Id = 5,
                            Description = "Kem dâu tươi mát lạnh",
                            DishCategoryId = 3,
                            IsAvailable = false,
                            Name = "Kem dâu",
                            PreparationTime = 5,
                            Price = 25000m
                        });
                });

            modelBuilder.Entity("KTGIUAKY.Models.DishImage_BCS240047", b =>
                {
                    b.HasOne("KTGIUAKY.Models.Dish_BCS240047", "Dish")
                        .WithMany("DishImages")
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dish");
                });

            modelBuilder.Entity("KTGIUAKY.Models.Dish_BCS240047", b =>
                {
                    b.HasOne("KTGIUAKY.Models.DishCategory_BCS240047", "DishCategory")
                        .WithMany("Dishes")
                        .HasForeignKey("DishCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DishCategory");
                });

            modelBuilder.Entity("KTGIUAKY.Models.DishCategory_BCS240047", b =>
                {
                    b.Navigation("Dishes");
                });

            modelBuilder.Entity("KTGIUAKY.Models.Dish_BCS240047", b =>
                {
                    b.Navigation("DishImages");
                });
#pragma warning restore 612, 618
        }
    }
}
